language: go

go:
  - master # This uses automatically the latest version of go

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  #- go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI
  - rm -rf docs || exit 0

script:
  - hugo # This commands builds your website on travis

# Deploy to GitHub pages
deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  local-dir: docs
  fqdn: shubhamnishad.com
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master  
