language: go

go:
  - master # This uses automatically the latest version of go

# using this for snap packages https://docs.travis-ci.com/user/installing-dependencies/#Installing-Snap-Packages
sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
  - rm -rf docs || exit 0

script:
  #- hugo # This commands builds your website on travis
  - /snap/bin/hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  local-dir: docs
  fqdn: shubhamnishad.com
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master  
