baseURL = "https://shubhamnishad.com"
languageCode = "en-us"
title = "Shubham Nishad"
theme="amp"
copyright = "© 2019 Copyright Text"
canonifyurls = true
pluralizelisttitles = false
publishDir = "docs"
SectionPagesMenu = "main"

[params]
  description = "I'm a Computer Science student, Learner, Reader and upcoming Software Engineer"
  defaultKeywords = "software,computer,it,software developer,shubham nishad,shubhamnishad,blog,student,internship,job,technology, canada, work permit, ottawa"

# optional
[social]
  twitter = "shubhamnishad97"
  github = "shubhamnishad97"
  facebook = "shubham.nishad.97"
  angellist = "shubhamnishad97"
  linkedin = "shubhamnishad"