baseURL = "https://shubhamnishad.com"
languageCode = "en-us"
title = "Shubham Nishad"
theme="amp"
copyright = "© 2017 Copyright Text"
canonifyurls = true
pluralizelisttitles = false
publishDir = "docs"
SectionPagesMenu = "main"

[params]
  description = "I'm a Computer Science student,Learner,Reader and upcoming Software Engineer"
  googleanalytics = "UA-101629128-1" # optional
  stylesheet = ["font-awesome.min.css"]
  defaultKeywords = "software,computer,it,software engineer,shubham nishad,shubhamnishad,blog,student,internship,job,technology"

# optional
[social]
  twitter = "shubhamnishad97"
  github = "shubhamnishad97"
  facebook = "shubham.nishad.97"
  angellist = "shubhamnishad97"
  linkedin = "shubham-nishad-3b401a129"