baseURL = "https://shubhamnishad.com"
languageCode = "en-us"
title = "ShubhamNishad"
theme="amp"
copyright = "© 2017 Copyright Text"
canonifyurls = true
pluralizelisttitles = false
publishDir = "docs"
SectionPagesMenu = "main"

[params]
  description = "Computer Science student, learner, reader." #optional
  googleanalytics = "Your Tracking Id" # optional
  stylesheet = ["font-awesome.min.css"]

# optional
[social]
  twitter = "shubhamnishad97"
  github = "shubhamnishad97"
  facebook = "shubham.nishad.97"
  angellist = "shubhamnishad97"
  linkedin = "shubham-nishad-3b401a129"